name: Push NuGet package

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      version:
        required: true
        type: string
      project_file_path:
        required: true
        type: string

jobs:
  PushNugetPackage:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
          
      - name: Add GitHub Packages source
        run: dotnet nuget add source https://nuget.pkg.github.com/alifcapital/index.json --name github --username ${{ github.actor }} --password ${{ secrets.EVENTBUS_RABBITMQ_SECRET }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project_file_path }}

      - name: Pack the NuGet package
        run: dotnet pack ${{ inputs.project_file_path }} --configuration Release --output ./nupkgs -p:PackageId="${{ inputs.package_name }}" -p:Version="${{ inputs.version }}"

      - name: Push the package to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source "https://nuget.pkg.github.com/alifcapital/index.json"