name: Release

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

permissions:
  contents: write  # Grant the workflow permission to push to the repository

jobs:
  Versioning:
    uses: ./.github/workflows/service-versioning.yml
    with:
      project_file_path: "src/InMemoryMessaging.csproj"
      should_add_version_tag: ${{ github.ref == 'refs/heads/main' }}
    secrets: inherit
  
  Release:
    needs: Versioning
    uses: ./.github/workflows/push-nuget-package.yml
    with:
      project_file_path: 'src/InMemoryMessaging.csproj'
      package_name: ${{ vars.PACKAGE_NAME }}
      version: ${{ needs.Versioning.outputs.version }}
    secrets: inherit
