name: Run tests of the service

on:
  workflow_call:
    inputs:
      postgres_image:
        required: false
        type: string
        default: postgres:16
      postgres_user:
        required: false
        type: string
        default: postgres
      postgres_password:
        required: false
        type: string
        default: postgres
      database_name:
        required: false
        type: string
        default: event_storage_db_test
      unit_and_functionality_tests_project_path:
        required: false
        type: string
        default: ""

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
          
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.unit_and_functionality_tests_project_path }}

      - name: Run unit and functionality tests
        run: dotnet test ${{ inputs.unit_and_functionality_tests_project_path }} --logger "console;verbosity=detailed" --blame
